---
title: "flat_dsm.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# My function

```{r function-prepare_dsm}

#' Obtenir dans le bon format les fichiers nécessaires aux analyses de distance sampling
#'
#' @param map_obj dataframe. La carte avec la densité associée
#' @param dist_obj dataframe. Les distances entre individus et transects
#' @param segs_obj dataframe. Les différents transects utilisés et leur coordonnées
#'
#' @importFrom dplyr select left_join filter mutate
#' @importFrom units drop_units
#' @importFrom sf st_centroid st_coordinates st_drop_geometry
#'
#' @return List. Les différents objects nécessaire pour faire du distance sampling.
#' @export

prepare_dsm <- function(map_obj, dist_obj, segs_obj) {
  
  obs_dsm <-   left_join(dist_obj, segs_obj, by='Sample.Label')  %>%
    select(object, Sample.Label, size, distance_m, detected) %>%
    drop_units() %>% 
    rename(distance = distance_m) %>%
    filter(detected == 1)
  
  dist_dsm <-  obs_dsm %>%
    select(object, distance) %>%
    drop_units()
  
  # segments
  segs_dsm <- segs_obj %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1]) %>%
    mutate(Y = st_coordinates(.)[,2]) %>%
    select(Effort, Sample.Label, X, Y) %>%
    st_drop_geometry() %>%
    drop_units()
  
  grid_dsm <- map_obj %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    drop_units() %>%
    as.data.frame() %>%
    select("X","Y","area")
  
  out <- list(dist_dsm = dist_dsm,
              obs_dsm = obs_dsm,
              segs_dsm = segs_dsm,
              grid_dsm = grid_dsm)
  
  return(out)
  
}
```

```{r examples-prepare_dsm}
# TO DO
```

```{r tests-prepare_dsm}
# TO DO
```

# My function

```{r function-get_var_dsm}

#' Recuperer des estimations de variance
#'
#' @param grid_obj dataframe. La grille de prédiction du modele
#' @param dsm_obj dsm objet. Le modele dsm créé
#'
#' @importFrom dsm dsm.var.gam 
#' @importFrom stats qnorm
#'
#' @return List. Une liste avec le cv, le se et l'intervalle de confiance à 95% 
#' @export


get_var_dsm <- function(grid_obj, dsm_obj) {
  
  
  # Récupération variance
  pred_dsm_var <- split(grid_obj, 1:nrow(grid_obj))
  
  dsm_var <- dsm.var.gam(dsm.obj = dsm_obj, 
                         pred.data = grid_obj,
                         off.set = grid_obj$area)
  
  sum_data <- summary(dsm_var)
  
  unconditional.cv.square <- sum_data$cv^2
  
  asymp.ci.c.term <- exp(qnorm(1-sum_data$alpha/2) * sqrt(log(1+unconditional.cv.square)))
  
  asymp.tot <- c(sum_data$pred.est / asymp.ci.c.term,
                sum_data$pred.est,
                sum_data$pred.est * asymp.ci.c.term)
  
  out <- list(CI = asymp.tot,
              cv = sum_data$cv,
              se = sum_data$se)
  
  return(out)

}

```

```{r examples-get_var_dsm}
# TO DO
```

```{r tests-get_var_dsm}
# TO DO
```


# Plot dsm

```{r function-plot_dsm}
#' Plot dsm
#'
#' @param dsm_pred_obj dsm object. Le modele dsm créé. 
#' @param map_obj dataframe. La carte avec la densité associée
#' @param title character. Le titre souhaité pour le graphique
#' @param legend character. La légende souhiatée pour le graphique
#'
#' @importFrom dplyr mutate
#' @importFrom ggplot2 ggplot geom_sf aes coord_sf scale_fill_gradientn labs theme element_text theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom viridisLite viridis
#' @importFrom sp bbox
#' @importFrom sf as_Spatial
#'
#' @return plot. La zone d'étude avec ce que le modèle a predit.
#' @export 

plot_dsm <- function(dsm_pred_obj, map_obj, title = "Detection", legend = "Marsouins\n(ind/km2)"){

  dsm_pred_plot  <- map_obj %>%
    as.data.frame() %>%
    mutate(density = dsm_pred_obj)

  theme_set(theme_bw())

  xlim <- bbox(as_Spatial(map_obj))[1, ]
  ylim <- bbox(as_Spatial(map_obj))[2, ]

  ggplot() +
    geom_sf(data = dsm_pred_plot$geometry, aes(fill = dsm_pred_plot$density), color = NA) +
    coord_sf(xlim = xlim, ylim = ylim) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "tr",
                           which_north = "true",
                           height = unit(1, "cm"),
                           width = unit(1, "cm"),
                           pad_x = unit(0.2, "cm"),
                           pad_y = unit(0.1, "cm"),
                           style = north_arrow_fancy_orienteering) +
    scale_fill_gradientn(name = legend,
                         colors = viridis(256)) +
    labs(title = title) +
    theme(legend.position = "right",
          legend.key.width = unit(0.5, "cm"),
          plot.title = element_text(lineheight = 0.8, face = "bold"),
          axis.text = element_text(size = 8))
}
```

```{r examples-plot_dsm}
# TO DO
```

```{r tests-plot_dsm}
# TO DO
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_dsm.Rmd", 
               vignette_name = "DSM",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
