---
title: "flat_simulate_ind.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# Simuler des individus selon un processus inhomogene de Poisson

```{r function-simulate_ind}

#' Processus de poisson inhomogène
#'
#' @param map_obj sf. La carte contenant les information de densité
#' @param crs numeric. Le systeme de coordonées utilisé

#'
#' @importFrom dplyr mutate select filter
#' @importFrom sf st_centroid st_coordinates st_crs
#' @importFrom sp coordinates<- proj4string<- gridded<- CRS
#' @importFrom maptools as.im.SpatialGridDataFrame
#'
#' @return dataframe. Les localisations des individus.
#' @export

simulate_ind <- function(map_obj, crs){
  
  # Creation d'une grille
  grid <- map_obj %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    as.data.frame() %>%
    select("X","Y","density_m")
  
  
  # Convertie dans la classe grille
  coordinates(grid) <- ~ X + Y
  proj4string(grid) <- CRS(st_crs(crs)$proj4string)
  gridded(grid) <- TRUE
  X_grid <- maptools::as.im.SpatialGridDataFrame(grid)
  
  # Processus de poisson inhomogene
  ppp <- spatstat.core::rpoispp(lambda = X_grid, drop = TRUE)
  sim_ind <- data.frame(x = ppp$x, y = ppp$y)
  
  # Size à améliorer plus tard
  sim_ind <- sim_ind %>%
    mutate(size = 1)
  
  return(sim_ind)
  
}
```

```{r examples-simulate_ind}
# TO DO
```

```{r tests-simulate_ind}
#TO DO 
```


# Plot individual simulated


```{r function-plot_obs}

#' Plot obs
#'
#' @param obs_obj dataframe. Les individus simulés et leur localisation. 
#' @param map_obj dataframe. La carte avec la densité associée
#' @param title character. Le titre souhaité pour le graphique
#' @param legend character. La légende souhiatée pour le graphique
#'
#' @importFrom ggplot2 ggplot geom_sf aes coord_sf scale_fill_gradientn geom_point scale_size labs theme element_text element_blank theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom viridisLite viridis
#' @importFrom sp bbox
#' @importFrom sf as_Spatial
#'
#' @return plot. La zone d'étude avec ce que le modèle a predit.
#' @export 

plot_obs <- function(obs_obj, map_obj, legend = "Marsouins\n(ind/km2)", title = ""){

  theme_set(theme_bw())

  xlim <- bbox(as_Spatial(map_obj))[1, ]
  ylim <- bbox(as_Spatial(map_obj))[2, ]

  ggplot() +
    geom_sf(data = map_obj, aes(fill = density_km), color = NA) +
    geom_point(data = obs_obj, aes(x = x, y = y), size = 0.5) +
    scale_size(name = "Nb ind", breaks = 0:3) +
    coord_sf(xlim = xlim, ylim = ylim) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "tr",
                           which_north = "true",
                           height = unit(0.8, "cm"),
                           width = unit(0.8, "cm"),
                           pad_x = unit(0.2, "cm"),
                           pad_y = unit(0.1, "cm"),
                           style = north_arrow_fancy_orienteering) +
    scale_fill_gradientn(name = legend,
                         colors = viridis(256)) +
    labs(title = title,
         caption = paste("Nb simulations = ", nrow(obs_obj), sep = " ")) +
    theme(legend.position = "right",
          legend.key.width = unit(0.5, "cm"),
          plot.title = element_text(lineheight = 0.8, face = "bold"),
          axis.text = element_text(size = 6),
          axis.title.x = element_blank(),
          axis.title.y = element_blank())
}
```

```{r examples-plot_obs}
# TO DO
```

```{r tests-plot_obs}
#TO DO 
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_simulate_ind.Rmd", 
               vignette_name = "Simulate individuals",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
