---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# Extraire une carte avec les densités souhaitées.

La permet de choisir le nombre d'individu dans la zone d'étude et de redéfinir la densité proportionnellement à la carte de densité précédemment créée.

```{r function-extract_map}

#' Extraire une carte avec les densités souhaitées
#'
#' @param density_obj Density object form dsims package. La carte contenant les densités.
#' @param N Numeric. Le nombre d'individus dans la zone d'étude
#' @param crs Numeric. Le système de coordonnées utilisé.
#'
#' @importFrom sf st_sf st_area
#' @importFrom dplyr mutate pull
#' @importFrom units drop_units
#'
#' @return sf object. La carte avec les densité souhaitées. 
#' @export


extract_map <- function(density_obj, N, crs) {
  
  map_obj <- density_obj@density.surface %>%
    as.data.frame() %>%
    st_sf(crs = crs) %>%
    mutate(area = st_area(.)) %>%
    mutate(area_grid = density_obj@x.space * density_obj@y.space) %>%
    drop_units() %>%
    filter(area == area_grid)
  
  area <- sum(map_obj$area)
  
  average_density_m <- N / area
  
  map_obj <- map_obj %>%
    mutate(density_m = average_density_m * density / mean(density, na.rm = TRUE)) %>%
    mutate(density_km = (average_density_m * density / mean(density, na.rm = TRUE)) * 1000000) %>%

  
  return(map_obj)
  
}

```

```{r examples-extract_map}
# TO DO

```

```{r tests-extract_map}
# TO DO 
```

# Plot individual simulated


```{r function-plot_map}

#' Plot map
#'
#' @param map_obj dataframe. La carte avec la densité associée
#' @param title character. Le titre souhaité pour le graphique
#' @param legend character. La légende souhiatée pour le graphique
#'
#' @importFrom ggplot2 ggplot geom_sf aes coord_sf scale_fill_gradientn geom_point scale_size labs theme element_text element_blank theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom viridisLite viridis
#' @importFrom sp bbox
#' @importFrom sf as_Spatial
#'
#' @return plot. La zone d'étude avec ce que le modèle a predit.
#' @export 

plot_map <- function(map_obj, legend = "Marsouins\n(ind/km2)", title = ""){

  theme_set(theme_bw())

  xlim <- bbox(as_Spatial(map_obj))[1, ]
  ylim <- bbox(as_Spatial(map_obj))[2, ]

  ggplot() +
    geom_sf(data = map_obj, aes(fill = density_km), color = NA) +
    scale_size(name = "Nb ind", breaks = 0:3) +
    coord_sf(xlim = xlim, ylim = ylim) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "tr",
                           which_north = "true",
                           height = unit(0.8, "cm"),
                           width = unit(0.8, "cm"),
                           pad_x = unit(0.2, "cm"),
                           pad_y = unit(0.1, "cm"),
                           style = north_arrow_fancy_orienteering) +
    scale_fill_gradientn(name = legend,
                         colors = viridis(256)) +
    theme(legend.position = "right",
          legend.key.width = unit(0.5, "cm"),
          plot.title = element_text(lineheight = 0.8, face = "bold"),
          axis.text = element_text(size = 6),
          axis.title.x = element_blank(),
          axis.title.y = element_blank())
}
```

```{r examples-plot_map}
# TO DO
```

```{r tests-plot_map}
#TO DO 
```



```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_extract_map.Rmd", 
               vignette_name = "Extract map",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
