---
title: "flat_prepare_dsm.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# My function

```{r function-prepare_dsm}

#' Obtenir dans le bon format les fichiers nécessaires aux analyses de distance sampling
#'
#' @param map_data dataframe. La carte avec la densité associée
#' @param dist_data dataframe. Les distances entre individus et transects
#' @param segs_data dataframe. Les différents transects utilisés et leur coordonnées
#'
#' @importFrom dplyr select left_join filter mutate
#' @importFrom units drop_units
#' @importFrom sf st_centroid st_coordinates st_drop_geometry
#'
#' @return List. Les différents objects nécessaire pour faire du distance sampling.
#' @export
#'
#' @examples
prepare_dsm <- function(map_data, dist_data, segs_data) {

  obs_dsm <-   left_join(dist_data,segs_data,by='Sample.Label')  %>%
    select(object, Sample.Label, size, distance, detected) %>%
    drop_units() %>%
    filter(detected == 1)

  dist_dsm <-  obs_dsm %>%
    select(object, distance) %>%
    drop_units()

  # segments
  segs_dsm <- segs_data %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1]) %>%
    mutate(Y = st_coordinates(.)[,2]) %>%
    select(Effort, Sample.Label, X, Y) %>%
    st_drop_geometry() %>%
    drop_units()

  grid_dsm <- map_data %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    drop_units() %>%
    as.data.frame() %>%
    select("X","Y","area")

  x <- list(dist_dsm = dist_dsm,
            obs_dsm = obs_dsm,
            segs_dsm = segs_dsm,
            grid_dsm = grid_dsm)

  return(x)

}
```

```{r examples-prepare_dsm}
# TO DO
```

```{r tests-prepare_dsm}
# TO DO
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_prepare_dsm.Rmd", 
               vignette_name = "Prepare DSM",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
