# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)


test_that("plot_map works", {
  
  data("dataset_map")
  
  expect_true(inherits(plot_map(map_obj = dataset_map), "ggplot"))
  expect_true(inherits(plot_map, "function")) 
  
})


test_that("test erreur plot_obs", {
  
  data(iris)
  data("dataset_map")
  
  expect_error(object = plot_map(map_obj = iris))
  
  
  dataset_map_test <- dataset_map %>%
    rename(nop = density_km)
  
  expect_error(object = plot_map(map_obj = dataset_map_test))
  
  dataset_map_test <- dataset_map
  dataset_map_test$density_km[5] <- "nop"
  
  expect_error(object = plot_map(map_obj = dataset_map_test))
  
})
