# Generated by fusen: do not edit by hand

library(testthat)

test_that("esw_hn works", {
  expect_true(inherits(esw_hn, "function")) 
})


test_that("test conformite esw_hn", {
  
  expect_equal(round(esw_hn(sigma = 0.3), digits = 3),
               expected = 0.376)
  
  expect_is(esw_hn(sigma = 0.3), "numeric")
  
})

test_that("test erreur esw_hn", {
  
  expect_error(object = esw_hn(sigma = "haha"))
  
})
