# Generated by fusen: do not edit by hand

library(testthat)

test_that("scale_hn works", {
  expect_true(inherits(scale_hn, "function")) 
})


test_that("test conformite scale_hn", {
  
  expect_equal(round(scale_hn(esw = 0.16), digits=3),
               expected = 0.128)
  
  expect_is(scale_hn(esw = 0.16), "numeric")
  
})

test_that("test erreur scale_hn", {
  
  expect_error(object = scale_hn(esw = "haha"))
  
})
