# Generated by fusen: do not edit by hand

library(testthat)
library(assertthat)
library(dplyr)
library(sf)
library(sp)
library(maptools)
library(glue)

test_that("test erreur plot_obs", {
  
  data(iris)
  data("dataset_map")
  
  expect_error(object = plot_obs(obs_obj = iris, 
                                 map_obj = dataset_map))
  
  ind_test <- simulate_ind(map_obj = dataset_map,
                           crs = 2154)
  
  
  dataset_map_test <- dataset_map %>%
    rename(nop = density_km)
  
  expect_error(object = plot_obs(obs_obj = ind_test, 
                                 map_obj = dataset_map_test))
  
  dataset_map_test <- dataset_map
  dataset_map_test$density_km[5] <- "nop"
  
  expect_error(object = plot_obs(obs_obj = ind_test, 
                                 map_obj = dataset_map_test))
  
  
})
