# Generated by fusen: do not edit by hand


test_that("get_monitored_area works", {
  expect_true(inherits(get_monitored_area, "function")) 
})

test_that("test conformite get_monitored_area", {
  
  data("dataset_map")
  data("dataset_segs")
  
  test <- get_monitored_area(transect_obj = dataset_segs,
                             map_obj = dataset_map,
                             truncation_m = 400)
  
  exp <- structure(238231771.712143, units = structure(list(numerator = c("m", 
"m"), denominator = character(0)), class = "symbolic_units"), class = "units")
  
  expect_equal(object = test,
               expected = exp)
  
  
})

test_that("test erreur extract_map", {
  
  data(iris)
  data("dataset_map")
  data("dataset_segs")
  
  expect_error(object = get_monitored_area(transect_obj = iris,
                                           map_obj = dataset_map,
                                           truncation_m = 400))
  
  expect_error(object = get_monitored_area(transect_obj = dataset_segs,
                                           map_obj = iris,
                                           truncation_m = 400))
  
  expect_error(object = get_monitored_area(transect_obj = dataset_segs,
                                           map_obj = dataset_map,
                                           truncation_m = iris))
  
})
