# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)
library(dssd)


test_that("plot_detect works", {
  
  data("dataset_segs")
  data("dataset_map")
  data("dataset_detected")
  
  expect_true(inherits(plot_detect(dist_obj = dataset_detected, 
                                   transect_obj = dataset_segs, 
                                   map_obj = dataset_map, 
                                   title = ""), "ggplot"))
  
  expect_true(inherits(plot_detect, "function")) 
})


test_that("test erreur plot_detect", {
  
  data(iris)
  data("dataset_segs")
  data("dataset_map")
  data("dataset_detected")
  
  expect_error(object = plot_detect(dist_obj = iris, 
                                   transect_obj = dataset_segs, 
                                   map_obj = dataset_map, 
                                   title = ""))
  
  expect_error(object = plot_detect(dist_obj = dataset_detected, 
                                   transect_obj = iris, 
                                   map_obj = dataset_map, 
                                   title = ""))
  
    expect_error(object = plot_detect(dist_obj = dataset_detected, 
                                   transect_obj = dataset_segs, 
                                   map_obj = iris, 
                                   title = ""))
    
}) 
