# Generated by fusen: do not edit by hand


#' Calculate distance between transects and points
#'
#' @param obs_obj sf object. Les individus simules
#' @param transect_obj sf object. Les segments de transects
#' @param crs numeric. Le systeme de coordonnes geographiques
#'
#' @importFrom dplyr select rename mutate n
#' @importFrom sf st_as_sf st_nearest_feature st_distance
#' @importFrom units drop_units

#'
#' @return dataframe. Un tableau donnant les distances par rapport aux individus et le segment associÃ©.
#' @export


#' @examples
#' # TO DO
calculate_distance <- function(obs_obj, transect_obj, crs){
  
  # On crÃ©e la couche de points obs
  dsf <- obs_obj %>%
    select("x","y") %>%
    st_as_sf(coords = c("x","y"), crs = crs)
  
  # On regarde quel est le segment de transect le plus proche
  nearest_spee <- st_nearest_feature(x = dsf, y = transect_obj)
  
  # On calcule la distance entre le transect et l'obs
  dist_obj <- st_distance(dsf, transect_obj[nearest_spee,], by_element=TRUE)
  
  # On crÃ©e un tableau rÃ©capitulatif
  dist_obj <- dist_obj %>%
    as.data.frame() %>%
    rename(distance_m = '.') %>%
    mutate(transect_obj[nearest_spee,'Sample.Label'],
           size = obs_obj$size,
           distance_km = distance_m / 1e3,) %>%
    mutate(x = obs_obj$x) %>%
    mutate(y = obs_obj$y) %>%
    mutate(object = 1:n()) %>%
    drop_units()
  
  return(dist_obj)
  
}
