# Generated by fusen: do not edit by hand


#' Calculate distance between transects and points
#'
#' @param x sf object. Les individus simules
#' @param segments sf object. Les segments de transects
#' @param crs numeric. Le systeme de coordonnes geographiques
#'
#' @importFrom dplyr select rename mutate n
#' @importFrom sf st_as_sf st_nearest_feature st_distance
#' @importFrom units drop_units

#'
#' @return dataframe. Un tableau donnant les distances par rapport aux individus et le segment associÃ©.
#' @export


#' @examples
#' # TO DO
calculate_distance <- function(x, segments, crs){

  # On crÃ©e la couche de points obs
  dsf <- x %>%
    select("x","y") %>%
    st_as_sf(coords = c("x","y"), crs = crs)

  # On regarde quel est le segment de transect le plus proche
  nearest_spee <- st_nearest_feature(x = dsf, y = segments)

  # On calcule la distance entre le transect et l'obs
  dist <- st_distance(dsf, segments[nearest_spee,], by_element=TRUE)

  # On crÃ©e un tableau rÃ©capitulatif
  d <- dist %>%
    as.data.frame() %>%
    rename(distance = '.') %>%
    mutate(segments[nearest_spee,'Sample.Label'],
           size = x$size,
           distance_km = distance / 1e3,) %>%
    mutate(object = 1:n()) %>%
    drop_units()

  return(d)
  
}
