# Generated by fusen: do not edit by hand


#' Crop transect
#'
#' @param transect_obj sf dataframe. The transect data.
#' @param map_obj sf dataframe. Map of the study area with the density.
#'
#' @importFrom sf st_union st_intersection
#'
#' @return sf dataframe. The transect resize to match the density map grid.
#' @export

#' @examples
#' 
#' data(dataset_transects)
#' data(dataset_map)
#' 
#' # The transects do not correspond perfectly to the density map
#' plot_transects(transect_obj = dataset_transects, 
#'                map_obj = dataset_map, 
#'                crs = 2154)
#' 
#' # Crop transects
#' cropped_transects <- crop_transect(transect_obj = dataset_transects,
#'                                    map_obj = dataset_map)
#' 
#' # The transects correspond perfectly to the density map
#' plot_transects(transect_obj = cropped_transects, 
#'                map_obj = dataset_map, 
#'                crs = 2154)
#' 
crop_transect <- function(transect_obj, map_obj) {
  
  # function check
  
  assert_that(inherits(transect_obj, "sf"))
  assert_that(inherits(map_obj, "sf"))
  
  # function
  
  contour_obj <- map_obj %>%
    st_union()
  
  transect_out <- transect_obj %>%
    st_intersection(contour_obj)
  
  return(transect_out)
  
}

