# Generated by fusen: do not edit by hand


#' Crop transect
#'
#' @param transect_obj Dataframe. Les transects.
#' @param map_obj Dataframe. Le tableau avec les donnÃ©es de la carte
#'
#' @importFrom sf st_union st_intersection
#'
#' @return Dataframe. Les transects croppÃ©s sur la taille de la grille.
#' @export

#' @examples
#' # TO DO 
crop_transect <- function(transect_obj, map_obj) {
  
  contour_obj <- map_obj %>%
    st_union()
  
  
  transect_out <- transect_obj %>%
    st_intersection(contour_obj)
  
  return(transect_out)
  
}

