# Generated by fusen: do not edit by hand


#' Fonction de dÃ©tection
#'
#' @param dist_data Dataframe avec les donnees de distance
#' @param key character. Forme de la fonction de dÃ©tetcion "hn" ou "unif"
#' @param esw_km numeric. Effective strip width (km). Utile que pour la demi normale, sinon NA. Par dÃ©faut NA.
#' @param strip_prob numeric. Le parametre de la loi uniforme. Par dÃ©faut NA.
#' @param truncation_m numeric. A partir de quelle distance aucun individu ne peut Ãªtre dÃ©tectÃ©.
#'
#' @importFrom dplyr mutate
#' @importFrom stats rbinom
#'
#' @return dataframe. Le tableau des distances avec en plus l'ajout de colonnes de porbabilitÃ© de dÃ©tection et de la dÃ©tection 1/0 calculÃ©e.
#' @export


detection <- function(dist_data, key, esw_km = NA, strip_prob = NA, truncation_m) {
  
  if(key == 'hn'){
    sigma <- scale_hn(esw = esw_km)
    dist_data <- dist_data %>%
      mutate(proba = exp(-(distance_km)^2 / (2 * sigma * sigma))) %>%
      mutate(detected = rbinom(nrow(dist_data), size = 1, prob = proba))
    
    dist_data$detected[dist_data$distance_m > truncation_m] <- 0
  }
  
  if(key == 'unif'){
    dist_data <- dist_data %>%
      mutate(proba = strip_prob) %>%
      mutate(detected = rbinom(nrow(dist_data), size = 1, prob = proba))
    
    dist_data$detected[dist_data$distance > truncation_m] <- 0
    dist_data$proba[dist_data$distance > truncation_m] <- 0
  }
  
  return(dist_data)
  
}
