# Generated by fusen: do not edit by hand


#' Esw_hn
#'
#' @param sigma Numeric. Le sigma d'une fonction demi normale
#' @param w Numeric. Je ne sais pas
#'
#' @importFrom stats pnorm dnorm
#'
#' @return Numeric. La valeur de esw associÃ©e au sigma.
#' @export

esw_hn <- function(sigma, w = +Inf){
  esw <- (pnorm(w, 0, sigma) - 0.5) / dnorm(0, 0, sigma)
  return(esw)
  }

