# Generated by fusen: do not edit by hand


#' Extraire une carte avec les densitÃ©s souhaitÃ©es
#'
#' @param obj_dens Density object form dsims package. La carte contenant les densitÃ©s.
#' @param N Numeric. Le nombre d'individus dans la zone d'Ã©tude
#' @param crs Numeric. Le systÃ¨me de coordonnÃ©es utilisÃ©.
#'
#' @importFrom sf st_sf st_area
#' @importFrom dplyr mutate pull
#' @importFrom units drop_units
#'
#' @return sf object. La carte avec les densitÃ© souhaitÃ©es. 
#' @export
#'
#' @examples

#' # TO DO
#' 
extract_map <- function(obj_dens, N, crs) {
  
  map <- obj_dens@density.surface %>%
    as.data.frame() %>%
    st_sf(crs = crs) %>%
    mutate(area = st_area(.)) %>%
    drop_units()
  
  area <- sum(map$area)
  
  average_density_per_m <- N / area
  
  map <- map %>%
    mutate(density_per_m = average_density_per_m * density / mean(density, na.rm = TRUE)) %>%
    mutate(density_per_km = (average_density_per_m * density / mean(density, na.rm = TRUE)) * 1000000) %>%
    mutate(area_grid = obj_dens@x.space * obj_dens@y.space)
  
  return(map)
  
}

