# Generated by fusen: do not edit by hand


#' Extraire une carte avec les densitÃ©s souhaitÃ©es
#'
#' @param density_obj Density object form dsims package. La carte contenant les densitÃ©s.
#' @param N Numeric. Le nombre d'individus dans la zone d'Ã©tude
#' @param crs Numeric. Le systÃ¨me de coordonnÃ©es utilisÃ©.
#'
#' @importFrom sf st_sf st_area
#' @importFrom dplyr mutate pull
#' @importFrom units drop_units
#'
#' @return sf object. La carte avec les densitÃ© souhaitÃ©es. 
#' @export


#' @examples
#' # TO DO
#' 
extract_map <- function(density_obj, N, crs) {
  
  map_obj <- density_obj@density.surface %>%
    as.data.frame() %>%
    st_sf(crs = crs) %>%
    mutate(area = st_area(.)) %>%
    mutate(area_grid = density_obj@x.space * density_obj@y.space) %>%
    drop_units() %>%
    filter(area == area_grid)
  
  area <- sum(map_obj$area)
  
  average_density_m <- N / area
  
  map_obj <- map_obj %>%
    mutate(density_m = average_density_m * density / mean(density, na.rm = TRUE)) %>%
    mutate(density_km = (average_density_m * density / mean(density, na.rm = TRUE)) * 1000000) %>%

  
  return(map_obj)
  
}

