# Generated by fusen: do not edit by hand


#' Obetnir l'aire de la zone d'Ã©tude qui est controlÃ©e par les transects
#'
#' @param transect_obj dataframe. Les transects 
#' @param map_obj dataframe. La carte de densitÃ©
#' @param truncation_m numeric. La distance Ã  laquelle on ne peut plus observer d'animaux. En m.
#'
#' @importFrom sf st_sf st_buffer st_union st_intersection st_area
#'
#' @return numeric. L'aire de la surface d'Ã©tude monitorÃ©e en m
#' @export


#' @examples
#' # TO DO 
get_monitored_area <- function(transect_obj, map_obj, truncation_m) {
  
  contour_obj <- map_obj %>%
    st_union()
  
  out <- transect_obj %>%
    st_buffer(dist = truncation_m, endCapStyle = 'FLAT') %>%
    st_union %>%
    st_intersection(contour_obj) %>%
    st_area()
  
  return(out)
  
}
