# Generated by fusen: do not edit by hand


#' Recuperer des estimations de variance
#'
#' @param grid_obj dataframe. La grille de prÃ©diction du modele
#' @param dsm_obj dsm objet. Le modele dsm crÃ©Ã©
#'
#' @importFrom dsm dsm.var.gam 
#' @importFrom stats qnorm
#'
#' @return List. Une liste avec le cv, le se et l'intervalle de confiance Ã  95% 
#' @export


#' @examples
#' # TO DO
get_var_dsm <- function(grid_obj, dsm_obj) {
  
  
  # RÃ©cupÃ©ration variance
  pred_dsm_var <- split(grid_obj, 1:nrow(grid_obj))
  
  dsm_var <- dsm.var.gam(dsm.obj = dsm_obj, 
                         pred.data = grid_obj,
                         off.set = grid_obj$area)
  
  sum_data <- summary(dsm_var)
  
  unconditional.cv.square <- sum_data$cv^2
  
  asymp.ci.c.term <- exp(qnorm(1-sum_data$alpha/2) * sqrt(log(1+unconditional.cv.square)))
  
  asymp.tot <- c(sum_data$pred.est / asymp.ci.c.term,
                sum_data$pred.est,
                sum_data$pred.est * asymp.ci.c.term)
  
  out <- list(CI = asymp.tot,
              cv = sum_data$cv,
              se = sum_data$se)
  
  return(out)

}

