# Generated by fusen: do not edit by hand


#' Plot transect
#'
#' @param transects_data dataframe. Le tableau de donnÃ©es avec les transects.
#' @param region_data region object. L'object contenant les information sur la region crÃ©Ã©e
#' @param crs numeric. Le systeme de coordonnees utilisÃ©.
#' @param ifsegs TRUE/FALSE. Est-ce que les transects sont des segments ?
#'
#' @importFrom ggplot2 ggplot geom_sf aes coord_sf scale_colour_manual geom_point theme element_text theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom sp bbox
#' @importFrom sf as_Spatial st_sf
#' @importFrom grDevices rainbow
#'
#' @return plot. La carte de la region avec les transects.
#' @export

#' @examples
#' # TO DO 
plot_transects <- function(transects_data, region_data, crs, ifsegs) {

  contour <- region_data@region %>%
    st_sf(crs = crs)

  xlim <- bbox(as_Spatial(contour))[1, ]
  ylim <- bbox(as_Spatial(contour))[2, ]

  theme_set(theme_bw())

  if(ifsegs == FALSE){
    plot <- ggplot() +
      geom_sf(data = contour, aes(), color = "black", alpha = 0) +

      geom_sf(data = transects_data, aes(), color = "black") +
      coord_sf(xlim = xlim, ylim = ylim) +
      annotation_scale(location = "br", width_hint = 0.5) +
      annotation_north_arrow(location = "tr",
                             which_north = "true",
                             pad_x = unit(0.2, "cm"),
                             pad_y = unit(0.1, "cm"),
                             style = north_arrow_fancy_orienteering) +
      theme(plot.title = element_text(lineheight = 0.8, face = "bold"),
            axis.text = element_text(size = 12))
  }

  if(ifsegs == TRUE){
    pal <- rainbow(nrow(transects_data), s=.6, v=.9)[sample(1:nrow(transects_data),nrow(transects_data))]

    plot <-  ggplot() +
      geom_sf(data = contour, aes(), color = "black", alpha = 0) +
      geom_sf(data = transects_data, aes(colour=Sample.Label)) +
      coord_sf(xlim = xlim, ylim = ylim) +
      annotation_scale(location = "br", width_hint = 0.5) +
      annotation_north_arrow(location = "tr",
                             which_north = "true",
                             pad_x = unit(0.2, "cm"),
                             pad_y = unit(0.1, "cm"),
                             style = north_arrow_fancy_orienteering) +
      scale_colour_manual(values=pal) +
      theme(legend.position = "none")
  }
  return(plot)
}


