# Generated by fusen: do not edit by hand


#' Plot obs
#'
#' @param obs_data dataframe. Les individus simulÃ©s et leur localisation. 
#' @param map_data dataframe. La carte avec la densitÃ© associÃ©e
#' @param title character. Le titre souhaitÃ© pour le graphique
#' @param legend character. La lÃ©gende souhiatÃ©e pour le graphique
#'
#' @importFrom ggplot2 ggplot geom_sf aes coord_sf scale_fill_gradientn geom_point scale_size labs theme element_text element_blank theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom viridisLite viridis
#' @importFrom sp bbox
#' @importFrom sf as_Spatial
#'
#' @return plot. La zone d'Ã©tude avec ce que le modÃ¨le a predit.
#' @export 

#' @examples
#' # TO DO
plot_obs <- function(obs_data, map_data, legend = "Marsouins\n(ind/km2)", title = ""){

  theme_set(theme_bw())

  xlim <- bbox(as_Spatial(map_data))[1, ]
  ylim <- bbox(as_Spatial(map_data))[2, ]

  ggplot() +
    geom_sf(data = map_data, aes(fill = density_km), color = NA) +
    geom_point(data = obs_data, aes(x = x, y = y), size = 0.5) +
    scale_size(name = "Nb ind", breaks = 0:3) +
    coord_sf(xlim = xlim, ylim = ylim) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "tr",
                           which_north = "true",
                           height = unit(0.8, "cm"),
                           width = unit(0.8, "cm"),
                           pad_x = unit(0.2, "cm"),
                           pad_y = unit(0.1, "cm"),
                           style = north_arrow_fancy_orienteering) +
    scale_fill_gradientn(name = legend,
                         colors = viridis(256)) +
    labs(title = title,
         caption = paste("Nb simulations = ", nrow(obs_data), sep = " ")) +
    theme(legend.position = "right",
          legend.key.width = unit(0.5, "cm"),
          plot.title = element_text(lineheight = 0.8, face = "bold"),
          axis.text = element_text(size = 6),
          axis.title.x = element_blank(),
          axis.title.y = element_blank())
}
