# Generated by fusen: do not edit by hand


#' PLot detection
#'
#' @param dist_obj dataframe. Le tableau contenant les distance de chaque individu simulÃ© au transects.
#' @param transect_obj dataframe. Le tableau renseignant sur les transects.
#' @param map_obj dataframe. La carte de densitÃ©.
#' @param title character. Le titre souhiatÃ© pour le graphique.
#'
#' @importFrom ggplot2 ggplot geom_sf geom_point aes coord_sf scale_fill_gradientn labs theme element_text element_blank element_rect element_line theme_set theme_bw unit
#' @importFrom ggspatial annotation_scale annotation_north_arrow north_arrow_fancy_orienteering
#' @importFrom sp bbox
#' @importFrom sf as_Spatial st_sf st_union
#'
#' @return plot. Une carte mettant en Ã©vidence les individus dÃ©tectÃ©s.
#' @export

plot_detect <- function(dist_obj, transect_obj, map_obj, title) {

  # on veut les contours
  contour_obj <- map_obj %>%
    st_union()

  # bounding box
  xlim <- bbox(as_Spatial(contour_obj))[1, ]
  ylim <- bbox(as_Spatial(contour_obj))[2, ]

  # Plot detection
  theme_set(theme_bw(base_size = 12))
  ggplot() +
    geom_sf(data = transect_obj, color = "black") +
    geom_sf(data = contour_obj, aes(), color = "black", alpha = 0) +
    geom_point(data = dist_obj[dist_obj$detected == 0, ], aes(x = x, y = y), alpha = 0.3, shape = 20) +
    geom_point(data = dist_obj[dist_obj$detected == 1, ], aes(x = x, y = y), shape = 21, fill = "midnightblue") +
    coord_sf(xlim = xlim, ylim = ylim) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "tr",
                           which_north = "true",
                           pad_x = unit(0.2, "cm"),
                           pad_y = unit(0.1, "cm"),
                           style = north_arrow_fancy_orienteering) +
    labs(title = title, caption = paste("Sightings = ", sum(dist_obj$detected), sep = " ")) +
    theme(legend.position = "bottom",
          legend.key.width = unit(0.5, "cm"),
          legend.text = element_text(size = 6),
          plot.margin = unit(c(-1,0.1,-1,0.1), "cm"),
          panel.grid = element_line(colour = "transparent"),
          plot.title = element_text(lineheight = 0.2, face = "bold"),
          axis.text = element_text(size = 10),
          strip.background = element_rect(fill = "white"),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.background = element_rect(fill = "azure"),
          panel.border = element_rect(fill = NA))
}

