# Generated by fusen: do not edit by hand


#' Obtenir dans le bon format les fichiers nÃ©cessaires aux analyses de distance sampling
#'
#' @param map_data dataframe. La carte avec la densitÃ© associÃ©e
#' @param dist_data dataframe. Les distances entre individus et transects
#' @param segs_data dataframe. Les diffÃ©rents transects utilisÃ©s et leur coordonnÃ©es
#'
#' @importFrom dplyr select left_join filter mutate
#' @importFrom units drop_units
#' @importFrom sf st_centroid st_coordinates st_drop_geometry
#'
#' @return List. Les diffÃ©rents objects nÃ©cessaire pour faire du distance sampling.
#' @export
#'
#' @examples
#' # TO DO
prepare_dsm <- function(map_data, dist_data, segs_data) {

  obs_dsm <-   left_join(dist_data,segs_data,by='Sample.Label')  %>%
    select(object, Sample.Label, size, distance, detected) %>%
    drop_units() %>%
    filter(detected == 1)

  dist_dsm <-  obs_dsm %>%
    select(object, distance) %>%
    drop_units()

  # segments
  segs_dsm <- segs_data %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1]) %>%
    mutate(Y = st_coordinates(.)[,2]) %>%
    select(Effort, Sample.Label, X, Y) %>%
    st_drop_geometry() %>%
    drop_units()

  grid_dsm <- map_data %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    drop_units() %>%
    as.data.frame() %>%
    select("X","Y","area")

  x <- list(dist_dsm = dist_dsm,
            obs_dsm = obs_dsm,
            segs_dsm = segs_dsm,
            grid_dsm = grid_dsm)

  return(x)

}
