# Generated by fusen: do not edit by hand


#' Create a random density
#'
#' @param region region object. The region create with dsims
#' @param grid_m numeric. La taille des grilles qui sont des carrÃ© (cotÃ© du carrÃ© en m)
#' @param density_base numeric. La densitÃ© de base pour la carte
#' @param crs numeric. Le systeme de coordonnÃ©es gÃ©ographique
#' @param amplitude numeric. Le min et le max de l'amplitude des hotspots ajoutÃ©s 
#' @param sigma numeric. Le min et le max de l'Ã©tendue des hotspots ajoutÃ©s
#' @param nb_simu numeric. Nombre de hotspot a ajouter
#'
#' @importFrom dsims make.density add.hotspot
#' @importFrom sf st_sfc st_sf st_point st_contains as_Spatial
#' @importFrom sp bbox
#' @importFrom stats runif
#'
#' @return density object. La carte avec les densitÃ©s crÃ©es
#' @export

random_density <- function(region, grid_m, density_base, crs, amplitude, sigma, nb_simu){
  
  density <- make.density(region = region,
                          x.space = grid_m,
                          y.space = grid_m,
                          constant = density_base) # number of animal per mÂ²
  
  # on veut les contours
  contour <- region@region %>%
    st_sf(crs = crs)
  
  # bounding box
  xlim <- bbox(as_Spatial(contour))[1, ]
  ylim <- bbox(as_Spatial(contour))[2, ]
  
  
  for(i in 1:nb_simu){
    
    sigma_n <- runif(1, sigma[1], sigma[2])
    amplitude_n <- runif(1, amplitude[1], amplitude[2])
    
    x <- runif(1, xlim[1], xlim[2])
    y <- runif(1, ylim[1], ylim[2])
    
    point <- st_sfc(st_point(c(x,y)), crs = crs)
    a <- as.numeric(st_contains(contour, point))
    
    while(is.na(a==1)){
      
      x <- runif(1, xlim[1], xlim[2])
      y <- runif(1, ylim[1], ylim[2])
      
      point <- st_sfc(st_point(c(x,y)), crs = crs)
      
      a <- as.numeric(st_contains(contour, point))
    }
    
    density <- add.hotspot(object = density,
                           centre = c(x, y),
                           sigma = sigma_n,
                           amplitude = amplitude_n)
    
    rm(a, x, y, sigma_n, amplitude_n)
    
  }
  
  return(density)
}
