# Generated by fusen: do not edit by hand


#' Calculate the sigma parameter of a half normal function associated to a effective strip width
#'
#' This function comes from the pelaDSM package. This functions allows to calculate the sigma of a half normal detection function according to the effective strip width esw decided for the detection quality.
#' @param esw numeric. Effective strip width in km.
#' @param lower numeric. Lower range of search.
#' @param upper numeric. Upper range of search.
#'
#' @importFrom stats uniroot
#' @importFrom assertthat assert_that
#'
#' @return numeric. The sigma parmater of a half normal function associated with a esw value.  
#' @export


#' @examples
#' 
#' scale_hn(esw = 0.16)
#' # sigma = 0.128
#' 
scale_hn <- function(esw, lower = 1e-3, upper = 5) {
  
  assert_that(is.numeric(esw))
  res <- as.numeric(uniroot(function(x, ...) {esw_hn(sigma = x) - esw},
                            lower = lower,
                            upper = upper,
                            tol = 1e-8)[1])
  return(res)
}

