# Generated by fusen: do not edit by hand


#' Scale hn
#'
#' @param esw Numeric. effctive strip width
#' @param lower Numeric. lower
#' @param upper Numeric. upper
#' @param w Numeric. Je ne sais pas
#'
#' @importFrom stats uniroot
#'
#' @return numeric. Le sigma associÃ© Ã  l'esw dans le cas d'une demi normale 
#' @export


scale_hn <- function(esw, lower = 1e-3, upper = 5, w = +Inf) {
  res <- as.numeric(uniroot(function(x, ...) {esw_hn(sigma = x, w = w) - esw},
                            lower = lower,
                            upper = upper,
                            tol = 1e-8)[1])
  return(res)
}

