# Generated by fusen: do not edit by hand


#' Processus de poisson inhomogÃ¨ne
#'
#' @param map sf. La carte contenant les information de densitÃ©
#' @param crs numeric. Le systeme de coordonÃ©es utilisÃ©

#'
#' @importFrom dplyr mutate select filter
#' @importFrom sf st_centroid st_coordinates st_crs
#' @importFrom sp coordinates proj4string gridded
#'
#' @return dataframe. Les localisations des individus.
#' @export

#' @examples
#' # TO DO
simulate_ind <- function(map, crs){
  
  # Creation d'une grille
  grid <- map %>%
    filter(area == area_grid) %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    as.data.frame() %>%
    select("X","Y","density_per_m")
  
  
  # Convertie dans la classe grille
  coordinates(grid) <- ~ X + Y
  proj4string(grid) <- CRS(st_crs(crs)$proj4string)
  gridded(grid) <- TRUE
  X_grid <- maptools::as.im.SpatialGridDataFrame(grid)
  
  # Processus de poisson inhomogene
  ppp <- spatstat.core::rpoispp(lambda = X_grid, drop = TRUE)
  sim_ind <- data.frame(x = ppp$x, y = ppp$y)
  
  # Size Ã  amÃ©liorer plus tard
  sim_ind <- sim_ind %>%
    mutate(size = 1)
  
  return(sim_ind)
  
}
